# Generated by Django 4.2.5 on 2023-10-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Consulta'),
        ),
    ]
