# Generated by Django 4.2.5 on 2023-09-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterUniqueTogether(
            name='usuarios',
            unique_together={('correo',)},
        ),
    ]
