# Generated by Django 4.2.5 on 2023-09-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(verbose_name='Fecha de reserva')),
                ('hora_reserva', models.TimeField(verbose_name='Hora de reserva')),
                ('usuario', models.ManyToManyField(to='usuarios.usuarios')),
            ],
        ),
    ]
