# Generated by Django 4.2.5 on 2023-10-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_remove_reserva_first_name_remove_reserva_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='option',
            field=models.TimeField(default='', verbose_name='Horario'),
        ),
    ]
